### ISSUE TITLE
No JSON support

### ISSUE THREAD

**Issue by henhuy** [OpenEnergyPlatform/oedialect#3]
I wanted to use JSON column type in my table with oedialect.
It is possible to create the table with column of type JSON, but uploading of json or dict goes wrong...
On my own postgresql database everything works fine! (I also tried it with postgresql type JSONB, but oedialect doesn't know this type...)

Code looks sonehow like this (changed some names):
```
# Table setup:
class TestTable(Base):
    __tablename__ = 'test_table'
    __table_args__ = {'schema': 'sandbox'}

    id = Column(INTEGER, primary_key=True)
    meta = Column(JSON)

# Insert into table:
meta = {
    'a': 'test',
    'b': 'test2'
}
table = TestTable(meta=meta)
session.add(table)
session.commit()
```
Responding error is (exchanged USERNAME):
`oedialect.engine.ConnectionException: DataError('invalid input syntax for type json\nLINE 1: ...r, id, meta) VALUES (NULL, \'<USERNAME>\', 1, \'{a: test,...\n                                                             ^\nDETAIL:  Token "a" is invalid.\nCONTEXT:  JSON data, line 1: {a...\n',)
`
I think somehow the oedialect escapes to early from data!? That's why its thinking 'a' is my Token...??
Thanks for any help!

**Comment by Ludee** [comment]
Since @henhuy is on vacation I can answer.
Our shared env uses this version:
sqlalchemy                1.1.13                   py35_0    conda-forge

**Comment by MGlauer** [comment]
@Ludee  I guess you answered the wrong issue ;)

**Comment by Ludee** [comment]
yes. I mixed up the issues.

**Comment by henhuy** [comment]
Thank you very much!

**Comment by henhuy** [comment]
Just tried your new solution - but still not working correctly.
1. One little thing: Updated to newest version, but if I don't add your suggestion  (thanks!)

> json_serializer=lambda x: x,
> json_deserializer=lambda x: x

creating of table containing column with type JSON still fails with `DataError` (from above). But with your suggestion creation of table worked.
2. I still can not add json data to the table...
The minimal example:
```
from sqlalchemy.ext.declarative import declarative_base
import sqlahelper
import transaction

Base = declarative_base()

class OEPTimeseries(Base):
    __tablename__ = 'table_with_json'
    __table_args__ = {'schema': SCHEMA}

    id = Column(BIGINT, primary_key=True)
    name = Column(VARCHAR(50))
    meta = Column(JSON)

meta = {'a': 'test', 'b': 'data'}
test = OEPTimeseries(
        name='Test',
        meta=meta
    )
session = sqlahelper.get_session()
session.add(test)
transaction.commit()
```
fails with `oedialect.engine.ConnectionException: Key 'type' not found in {'a': 'test', 'b': 'data'}`.
Strange...

I get the feeling that setting up Tables via sqlalchemys `Base` class is not supported that well?
Maybe some things are slightly different?!
@MGlauer Did you tried to set up tables via `Base = declarative_base()` as well?

**Comment by henhuy** [comment]
Finally, I figured it out! It's very mean but simple error.
You shouldn't use `meta` as column name!
Apparently, it is a reserved variable name inside oedialect or sqlalchemy (i did not check where it crashes exactly).

I think there should be a warning/error message like:
`NameError('You are not allowed to use name "meta" as column identifier.')`
