### ISSUE TITLE
Using `&` inside `or_` in a `filter` doesn't work

### ISSUE THREAD

**Issue by gnn** [OpenEnergyPlatform/oedialect#31]
I'm trying to do something like

```python
pairs = [(1, 2), (3, 4)]
session.query(Column).filter(
    or_(((Column.value > p[0]) & (Column.value < p[1])) for p in pairs)
).all()
```

which works when using `psycopg2` but fails when using the `oedialect`.
The error is `Answer contains no JSON: <Response [500]>`, as usual. :)
The code above is just a simplified version of [the real, failing code][0].
You can also check out the [`pprint`ed request data][1]. And sorry for all
the noise in the request. I tried to cut it down but that's as far as I could do it.
Looking at this, I see that the nested filtering might be a red herring though.
The culprit could also be the `Timestamp`s at the bottom of the file, which the
server might not be able to decode.

[0]: https://github.com/oemof/feedinlib/commit/f9f3bcf9dafd95876fd67b4cf9bbcb4090d1cef7#diff-df115d3e8baa477a79d20c8db238d93aR222-R232
[1]: https://gist.github.com/gnn/6a33066068f13a61322a0bb64bf31f76

**Comment by MGlauer** [comment]
Branch `fix/clauselist-ops` should fix that
