### ISSUE TITLE
Unexpected behavior when creating an index on a table

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oedialect#34]
I develop a [tool](https://github.com/OpenEnergyPlatform/data-preprocessing/tree/feature/oep-upload-oem2orm/data-import/oep-upload) to generate a sqlachemy orm from the open ernergy metadata format and then create the tables with the oedialect on the OEP. This causes unexpected behavior when the tables are created (table.create(checkfirst=True)). 

The generated ORM looks like this:
```
[Table('bsh_seevermessung_deutsche_seegrenzen', 
MetaData(bind=Engine(postgresql+oedialect://Jonas.Huber:***@openenergy-platform.org)),
Column('fid', INTEGER(), table=<bsh_seevermessung_deutsche_seegrenzen>, primary_key=True,
nullable=False), Column('gml_id', TEXT(), table=<bsh_seevermessung_deutsche_seegrenzen>), 
Column('BESCHREIBUNG', TEXT(), table=<bsh_seevermessung_deutsche_seegrenzen>), 
Column('AUFLOESUNG', TEXT(), table=<bsh_seevermessung_deutsche_seegrenzen>), 
Column('QUELLE', TEXT(), table=<bsh_seevermessung_deutsche_seegrenzen>), 
Column('QUELLENBEZEICHNUNG', TEXT(), table=<bsh_seevermessung_deutsche_seegrenzen>), 
Column('QUELLENBESCHREIBUNG', TEXT(), table=<bsh_seevermessung_deutsche_seegrenzen>), 
Column('HINWEIS', TEXT(), table=<bsh_seevermessung_deutsche_seegrenzen>), Column('geom', 
Geometry(), table=<bsh_seevermessung_deutsche_seegrenzen>), schema='sandbox')]

```

When i execute the function table.create(checkfirst=True) for the first time the following expression appears:

```
C:\Anaconda3\envs\oep-upload\lib\site-packages\oedialect\engine.py in execute(self, query_obj, params)
    318         if not isinstance(query_obj, dict):
    319             if isinstance(query_obj, str):
--> 320                 raise Exception('Plain string commands are not supported.'
    321                                 'Please use SQLAlchemy datastructures')
    322             query = query_obj.string

Exception: Plain string commands are not supported.Please use SQLAlchemy datastructures
```

The second time I execute it, everything runs without errors and the tables are created.

I have debugged this, in my opinion the error occurs when creating the INDEX. 
```
ipdb> d
> c:\anaconda3\envs\oep-upload\lib\site-packages\oedialect\engine.py(320)execute()
    318         if not isinstance(query_obj, dict):
    319             if isinstance(query_obj, str):
--> 320                 raise Exception('Plain string commands are not supported.'
    321                                 'Please use SQLAlchemy datastructures')
    322             query = query_obj.string

ipdb> p query_obj
'CREATE INDEX "idx_bsh_seevermessung_deutsche_seegrenzen_geom" ON "sandbox"."bsh_seevermessung_deutsche_seegrenzen" USING GIST ("geom")'
```
I think the index is created via geoalchemy2

Is this a bug in oedialect?

**Comment by christian-rli** [comment]
@jh-RLI how have you debugged this? Or did you just find where the error occurs?

**Comment by jh-RLI** [comment]
@christian-rli  The just part :) I don't know how to fix this.

**Comment by MGlauer** [comment]
Well, the OEP-API does not support indices. It is still in discussion whether it ever will. It may be more beneficial if the OEP sets an index on those columns that are queried regularly.

**Comment by christian-rli** [comment]
> Well, the OEP-API does not support indices. It is still in discussion whether it ever will. It may be more beneficial if the OEP sets an index on those columns that are queried regularly.

@MGlauer Is it possible to suppress setting an index when calling `table.create(checkfirst=True)`? Also, why does it work the second time it's called?

I think it probably makes sense to set indices on regularly queried columns. Building indices into the API seems like an overshoot and something that can just be automated away.

**Comment by christian-rli** [comment]
@jh-RLI MGlauer suspects that it might be a bug in sql-alchemy's minor version. Those appear to happen from time to time. The reason why the error shows the first time, but not the second is that the table **is** created the first time, but the index could not be set. The second time the command is called, because we use "extend existing" it doesn't seem to try to set new indices. 

The mystery still is why it tries to set an index at all, as it should not actually do that. A workaround MGlauer suggested, which you also tried, I think, is to manually set index=False. So be sure to include that int the next release of oeo2orm :)

If the error persists, maybe share your sql-alchemy version number here for proper debugging.

**Comment by jh-RLI** [comment]
@christian-rli @MGlauer 
that's right the table is already created the first time you run it although an exception appears. the index on the table is created because in the column "geom" the data type "Geometry" is selected. This data type is imported from geoalchemy2 in [ome2orm.](https://github.com/OpenEnergyPlatform/data-preprocessing/blob/77169a89958b7836f44dd89c1f5b087668ee0409/data-import/oep-upload/oem2orm/postgresql_types.py#L28) Geoalchemy2 then creates the index for the table. Because the command is passed as string the oedialect is complaining here. Why the index is created anyway I do not know. To solve this we need another way to create the geometry column.

**Comment by jh-RLI** [comment]
I fixed it by setting "geometry": Geometry("GEOMETRY", spatial_index=False)

**Comment by jh-RLI** [comment]
I noticed that the index is still created. Maybe the OEDB set the index to geometry columns by default?

**Comment by jh-RLI** [comment]
since this is tested quite extensively I will close this Issue.
