### ISSUE TITLE
TypeError: _get_column_info

### ISSUE THREAD

**Issue by stefansc1** [OpenEnergyPlatform/oedialect#4]
Hi,

I'm having trouble getting the oedialect to run. Specifically, tables cannot be specified. Im getting a stacktrace that ends with

File "C:\Anaconda\envs\webmap\lib\site-packages\oedialect\dialect.py", line 375, in get_columns
    name, format_type, default, notnull, domains, enums, schema)
TypeError: _get_column_info() missing 1 required positional argument: 'comment'

This line seems to reference the postgresql dialect's base.py (https://github.com/zzzeek/sqlalchemy/blob/fb377229cd4c4e503bde9c44b78d30ad48f3cf7e/lib/sqlalchemy/dialects/postgresql/base.py#L2587). That function takes eight arguments, but is only given seven, missing 'comment'.

I'm using oedialect 0.0.1.dev0, installed with pip. My project works fine using the psycopg2 dialect.

**Comment by MGlauer** [comment]
Could you specify the version of sqlalchemy you are using?

**Comment by stefansc1** [comment]
1.2.10

**Comment by MGlauer** [comment]
The current OEP-API does not support comments, yet. Probably, this will change in the next minor release.
I will issue a patch with a workaround for this issue.

**Comment by stefansc1** [comment]
Thank you, this is fixed now.
