### ISSUE TITLE
Cannot dump data in post function

### ISSUE THREAD

**Issue by stefansc1** [OpenEnergyPlatform/oedialect#5]
In engine.py, post tries to dump and then load the given query. However, some keys are not strings but tuples, which json.dumps cannot encode (TypeError: keys must be a string). Example ('get_columns_raw', ('osm_deu_point',), (('schema', 'openstreetmap'),)) as a key in info_cache. A crude solution would be to go through the dictionary and sub-dictionaries and forcibly convert all keys to strings.

oedialect version: current (v0.0.2)
sqlAlchemy version: 1.2.10

**Comment by MGlauer** [comment]
I guess we can omit the `info_cache` entirely upon sending data to the OEP. This is a dictionary that contains data that has already been fetched and should be entirely local. The OEP stores it's own  `info_cache`. The  local  `info_cache` will be handed down until in the `kwargs` but not communicated to the OEP.
This seems to be the cleanest approach here.

**Comment by stefansc1** [comment]
What's the state of merging the request?

**Comment by MGlauer** [comment]
Done. I released a new version. 
FYI: You can install arbitrary arbitrary versions from any github branches regardless of the latest release:
`pip install git+https://github.com/OpenEnergyPlatform/oedialect.git@<branch-name>`
It is even possible to link against local instances of you packages by using the `-e` flag

**Comment by christian-rli** [comment]
I'm currently going through all OpenEnergyPlatform repositories to collect relevant issues for a specification_sheet. Also I'm trying to get familiar with the issues and code base. Whenever easily possible I'm trying to sort and close issues. 
This issue seems to be solved. Can it be closed?
