### ISSUE TITLE
Missing documentation for developpers

### ISSUE THREAD

**Issue by nesnoj** [OpenEnergyPlatform/oedialect#9]
Are you planning some kind of documentation?
A short description and some examples would be great. I started in #8.

**Comment by Bachibouzouk** [comment]
I have the impression that some examples are located [here](https://github.com/OpenEnergyPlatform/examples/tree/master/api)

**Comment by nesnoj** [comment]
Oh yea, more examples were added since I created this issue :+1:.
It'd be good to have an updated link in the [README.md](https://github.com/OpenEnergyPlatform/oedialect/blob/master/README.md).

@Bachibouzouk, you're the issue reviser of the month! :)

**Comment by Bachibouzouk** [comment]
> It'd be good to have an updated link in the [README.md](https://github.com/OpenEnergyPlatform/oedialect/blob/master/README.md).

@nesnoj - I'll do it

**Comment by nesnoj** [comment]
Cheers!

**Comment by Bachibouzouk** [comment]
It is in https://github.com/OpenEnergyPlatform/oedialect/pull/24
